// Code generated by go-swagger; DO NOT EDIT.

package r_u_m_metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteCalculatedMetricsRumReader is a Reader for the DeleteCalculatedMetricsRum structure.
type DeleteCalculatedMetricsRumReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCalculatedMetricsRumReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteCalculatedMetricsRumNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteCalculatedMetricsRumNoContent creates a DeleteCalculatedMetricsRumNoContent with default headers values
func NewDeleteCalculatedMetricsRumNoContent() *DeleteCalculatedMetricsRumNoContent {
	return &DeleteCalculatedMetricsRumNoContent{}
}

/*DeleteCalculatedMetricsRumNoContent handles this case with default header values.

Deleted. Response does not have a body.
*/
type DeleteCalculatedMetricsRumNoContent struct {
}

func (o *DeleteCalculatedMetricsRumNoContent) Error() string {
	return fmt.Sprintf("[DELETE /calculatedMetrics/rum/{metricKey}][%d] deleteCalculatedMetricsRumNoContent ", 204)
}

func (o *DeleteCalculatedMetricsRumNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
