// Code generated by go-swagger; DO NOT EDIT.

package r_u_m_metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// GetCalculatedMetricsRumsReader is a Reader for the GetCalculatedMetricsRums structure.
type GetCalculatedMetricsRumsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCalculatedMetricsRumsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCalculatedMetricsRumsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCalculatedMetricsRumsOK creates a GetCalculatedMetricsRumsOK with default headers values
func NewGetCalculatedMetricsRumsOK() *GetCalculatedMetricsRumsOK {
	return &GetCalculatedMetricsRumsOK{}
}

/*GetCalculatedMetricsRumsOK handles this case with default header values.

successful operation
*/
type GetCalculatedMetricsRumsOK struct {
	Payload *dynatrace.StubList
}

func (o *GetCalculatedMetricsRumsOK) Error() string {
	return fmt.Sprintf("[GET /calculatedMetrics/rum][%d] getCalculatedMetricsRumsOK  %+v", 200, o.Payload)
}

func (o *GetCalculatedMetricsRumsOK) GetPayload() *dynatrace.StubList {
	return o.Payload
}

func (o *GetCalculatedMetricsRumsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dynatrace.StubList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
