// Code generated by go-swagger; DO NOT EDIT.

package service_request_naming

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// UpdateServiceRequestNamingOrderReader is a Reader for the UpdateServiceRequestNamingOrder structure.
type UpdateServiceRequestNamingOrderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateServiceRequestNamingOrderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateServiceRequestNamingOrderNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateServiceRequestNamingOrderBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateServiceRequestNamingOrderNoContent creates a UpdateServiceRequestNamingOrderNoContent with default headers values
func NewUpdateServiceRequestNamingOrderNoContent() *UpdateServiceRequestNamingOrderNoContent {
	return &UpdateServiceRequestNamingOrderNoContent{}
}

/*UpdateServiceRequestNamingOrderNoContent handles this case with default header values.

Success. Request namings have been updated. Response doesn't have a body.
*/
type UpdateServiceRequestNamingOrderNoContent struct {
}

func (o *UpdateServiceRequestNamingOrderNoContent) Error() string {
	return fmt.Sprintf("[PUT /service/requestNaming/order][%d] updateServiceRequestNamingOrderNoContent ", 204)
}

func (o *UpdateServiceRequestNamingOrderNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateServiceRequestNamingOrderBadRequest creates a UpdateServiceRequestNamingOrderBadRequest with default headers values
func NewUpdateServiceRequestNamingOrderBadRequest() *UpdateServiceRequestNamingOrderBadRequest {
	return &UpdateServiceRequestNamingOrderBadRequest{}
}

/*UpdateServiceRequestNamingOrderBadRequest handles this case with default header values.

Failed. The input is invalid.
*/
type UpdateServiceRequestNamingOrderBadRequest struct {
	Payload *dynatrace.ErrorEnvelope
}

func (o *UpdateServiceRequestNamingOrderBadRequest) Error() string {
	return fmt.Sprintf("[PUT /service/requestNaming/order][%d] updateServiceRequestNamingOrderBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateServiceRequestNamingOrderBadRequest) GetPayload() *dynatrace.ErrorEnvelope {
	return o.Payload
}

func (o *UpdateServiceRequestNamingOrderBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dynatrace.ErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
