// Code generated by go-swagger; DO NOT EDIT.

package service_request_naming

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// ValidateUpdateServiceRequestNamingReader is a Reader for the ValidateUpdateServiceRequestNaming structure.
type ValidateUpdateServiceRequestNamingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateUpdateServiceRequestNamingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewValidateUpdateServiceRequestNamingNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewValidateUpdateServiceRequestNamingBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewValidateUpdateServiceRequestNamingNoContent creates a ValidateUpdateServiceRequestNamingNoContent with default headers values
func NewValidateUpdateServiceRequestNamingNoContent() *ValidateUpdateServiceRequestNamingNoContent {
	return &ValidateUpdateServiceRequestNamingNoContent{}
}

/*ValidateUpdateServiceRequestNamingNoContent handles this case with default header values.

Validated. The submitted configuration is valid. Response does not have a body.
*/
type ValidateUpdateServiceRequestNamingNoContent struct {
}

func (o *ValidateUpdateServiceRequestNamingNoContent) Error() string {
	return fmt.Sprintf("[POST /service/requestNaming/{id}/validator][%d] validateUpdateServiceRequestNamingNoContent ", 204)
}

func (o *ValidateUpdateServiceRequestNamingNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateUpdateServiceRequestNamingBadRequest creates a ValidateUpdateServiceRequestNamingBadRequest with default headers values
func NewValidateUpdateServiceRequestNamingBadRequest() *ValidateUpdateServiceRequestNamingBadRequest {
	return &ValidateUpdateServiceRequestNamingBadRequest{}
}

/*ValidateUpdateServiceRequestNamingBadRequest handles this case with default header values.

Failed. The input is invalid.
*/
type ValidateUpdateServiceRequestNamingBadRequest struct {
	Payload *dynatrace.ErrorEnvelope
}

func (o *ValidateUpdateServiceRequestNamingBadRequest) Error() string {
	return fmt.Sprintf("[POST /service/requestNaming/{id}/validator][%d] validateUpdateServiceRequestNamingBadRequest  %+v", 400, o.Payload)
}

func (o *ValidateUpdateServiceRequestNamingBadRequest) GetPayload() *dynatrace.ErrorEnvelope {
	return o.Payload
}

func (o *ValidateUpdateServiceRequestNamingBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dynatrace.ErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
