// Code generated by go-swagger; DO NOT EDIT.

package service_detection_full_web_request

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// NewValidateCreateServiceDetectionRuleFullRequestParams creates a new ValidateCreateServiceDetectionRuleFullRequestParams object
// with the default values initialized.
func NewValidateCreateServiceDetectionRuleFullRequestParams() *ValidateCreateServiceDetectionRuleFullRequestParams {
	var ()
	return &ValidateCreateServiceDetectionRuleFullRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewValidateCreateServiceDetectionRuleFullRequestParamsWithTimeout creates a new ValidateCreateServiceDetectionRuleFullRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewValidateCreateServiceDetectionRuleFullRequestParamsWithTimeout(timeout time.Duration) *ValidateCreateServiceDetectionRuleFullRequestParams {
	var ()
	return &ValidateCreateServiceDetectionRuleFullRequestParams{

		timeout: timeout,
	}
}

// NewValidateCreateServiceDetectionRuleFullRequestParamsWithContext creates a new ValidateCreateServiceDetectionRuleFullRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewValidateCreateServiceDetectionRuleFullRequestParamsWithContext(ctx context.Context) *ValidateCreateServiceDetectionRuleFullRequestParams {
	var ()
	return &ValidateCreateServiceDetectionRuleFullRequestParams{

		Context: ctx,
	}
}

// NewValidateCreateServiceDetectionRuleFullRequestParamsWithHTTPClient creates a new ValidateCreateServiceDetectionRuleFullRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewValidateCreateServiceDetectionRuleFullRequestParamsWithHTTPClient(client *http.Client) *ValidateCreateServiceDetectionRuleFullRequestParams {
	var ()
	return &ValidateCreateServiceDetectionRuleFullRequestParams{
		HTTPClient: client,
	}
}

/*ValidateCreateServiceDetectionRuleFullRequestParams contains all the parameters to send to the API endpoint
for the validate create service detection rule full request operation typically these are written to a http.Request
*/
type ValidateCreateServiceDetectionRuleFullRequestParams struct {

	/*Body
	  The JSON body of the request. Contains parameters of the service detection rule to be validated.

	*/
	Body *dynatrace.FullWebRequestRule

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the validate create service detection rule full request params
func (o *ValidateCreateServiceDetectionRuleFullRequestParams) WithTimeout(timeout time.Duration) *ValidateCreateServiceDetectionRuleFullRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate create service detection rule full request params
func (o *ValidateCreateServiceDetectionRuleFullRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate create service detection rule full request params
func (o *ValidateCreateServiceDetectionRuleFullRequestParams) WithContext(ctx context.Context) *ValidateCreateServiceDetectionRuleFullRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate create service detection rule full request params
func (o *ValidateCreateServiceDetectionRuleFullRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate create service detection rule full request params
func (o *ValidateCreateServiceDetectionRuleFullRequestParams) WithHTTPClient(client *http.Client) *ValidateCreateServiceDetectionRuleFullRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate create service detection rule full request params
func (o *ValidateCreateServiceDetectionRuleFullRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the validate create service detection rule full request params
func (o *ValidateCreateServiceDetectionRuleFullRequestParams) WithBody(body *dynatrace.FullWebRequestRule) *ValidateCreateServiceDetectionRuleFullRequestParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the validate create service detection rule full request params
func (o *ValidateCreateServiceDetectionRuleFullRequestParams) SetBody(body *dynatrace.FullWebRequestRule) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateCreateServiceDetectionRuleFullRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
