// Code generated by go-swagger; DO NOT EDIT.

package service_detection_full_web_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteServiceDetectionRuleFullServiceParams creates a new DeleteServiceDetectionRuleFullServiceParams object
// with the default values initialized.
func NewDeleteServiceDetectionRuleFullServiceParams() *DeleteServiceDetectionRuleFullServiceParams {
	var ()
	return &DeleteServiceDetectionRuleFullServiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteServiceDetectionRuleFullServiceParamsWithTimeout creates a new DeleteServiceDetectionRuleFullServiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteServiceDetectionRuleFullServiceParamsWithTimeout(timeout time.Duration) *DeleteServiceDetectionRuleFullServiceParams {
	var ()
	return &DeleteServiceDetectionRuleFullServiceParams{

		timeout: timeout,
	}
}

// NewDeleteServiceDetectionRuleFullServiceParamsWithContext creates a new DeleteServiceDetectionRuleFullServiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteServiceDetectionRuleFullServiceParamsWithContext(ctx context.Context) *DeleteServiceDetectionRuleFullServiceParams {
	var ()
	return &DeleteServiceDetectionRuleFullServiceParams{

		Context: ctx,
	}
}

// NewDeleteServiceDetectionRuleFullServiceParamsWithHTTPClient creates a new DeleteServiceDetectionRuleFullServiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteServiceDetectionRuleFullServiceParamsWithHTTPClient(client *http.Client) *DeleteServiceDetectionRuleFullServiceParams {
	var ()
	return &DeleteServiceDetectionRuleFullServiceParams{
		HTTPClient: client,
	}
}

/*DeleteServiceDetectionRuleFullServiceParams contains all the parameters to send to the API endpoint
for the delete service detection rule full service operation typically these are written to a http.Request
*/
type DeleteServiceDetectionRuleFullServiceParams struct {

	/*ID
	  The ID of the service detection rule to be deleted.

	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete service detection rule full service params
func (o *DeleteServiceDetectionRuleFullServiceParams) WithTimeout(timeout time.Duration) *DeleteServiceDetectionRuleFullServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete service detection rule full service params
func (o *DeleteServiceDetectionRuleFullServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete service detection rule full service params
func (o *DeleteServiceDetectionRuleFullServiceParams) WithContext(ctx context.Context) *DeleteServiceDetectionRuleFullServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete service detection rule full service params
func (o *DeleteServiceDetectionRuleFullServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete service detection rule full service params
func (o *DeleteServiceDetectionRuleFullServiceParams) WithHTTPClient(client *http.Client) *DeleteServiceDetectionRuleFullServiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete service detection rule full service params
func (o *DeleteServiceDetectionRuleFullServiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete service detection rule full service params
func (o *DeleteServiceDetectionRuleFullServiceParams) WithID(id strfmt.UUID) *DeleteServiceDetectionRuleFullServiceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete service detection rule full service params
func (o *DeleteServiceDetectionRuleFullServiceParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteServiceDetectionRuleFullServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
