// Code generated by go-swagger; DO NOT EDIT.

package maintenance_windows

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// NewUpdateMaintenanceWindowParams creates a new UpdateMaintenanceWindowParams object
// with the default values initialized.
func NewUpdateMaintenanceWindowParams() *UpdateMaintenanceWindowParams {
	var ()
	return &UpdateMaintenanceWindowParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateMaintenanceWindowParamsWithTimeout creates a new UpdateMaintenanceWindowParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateMaintenanceWindowParamsWithTimeout(timeout time.Duration) *UpdateMaintenanceWindowParams {
	var ()
	return &UpdateMaintenanceWindowParams{

		timeout: timeout,
	}
}

// NewUpdateMaintenanceWindowParamsWithContext creates a new UpdateMaintenanceWindowParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateMaintenanceWindowParamsWithContext(ctx context.Context) *UpdateMaintenanceWindowParams {
	var ()
	return &UpdateMaintenanceWindowParams{

		Context: ctx,
	}
}

// NewUpdateMaintenanceWindowParamsWithHTTPClient creates a new UpdateMaintenanceWindowParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateMaintenanceWindowParamsWithHTTPClient(client *http.Client) *UpdateMaintenanceWindowParams {
	var ()
	return &UpdateMaintenanceWindowParams{
		HTTPClient: client,
	}
}

/*UpdateMaintenanceWindowParams contains all the parameters to send to the API endpoint
for the update maintenance window operation typically these are written to a http.Request
*/
type UpdateMaintenanceWindowParams struct {

	/*Body
	  The JSON body of the request. Contains updated parameters of the maintenance window.

	*/
	Body *dynatrace.MaintenanceWindow
	/*ID
	  The ID of the maintenance window to be updated.

	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update maintenance window params
func (o *UpdateMaintenanceWindowParams) WithTimeout(timeout time.Duration) *UpdateMaintenanceWindowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update maintenance window params
func (o *UpdateMaintenanceWindowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update maintenance window params
func (o *UpdateMaintenanceWindowParams) WithContext(ctx context.Context) *UpdateMaintenanceWindowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update maintenance window params
func (o *UpdateMaintenanceWindowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update maintenance window params
func (o *UpdateMaintenanceWindowParams) WithHTTPClient(client *http.Client) *UpdateMaintenanceWindowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update maintenance window params
func (o *UpdateMaintenanceWindowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update maintenance window params
func (o *UpdateMaintenanceWindowParams) WithBody(body *dynatrace.MaintenanceWindow) *UpdateMaintenanceWindowParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update maintenance window params
func (o *UpdateMaintenanceWindowParams) SetBody(body *dynatrace.MaintenanceWindow) {
	o.Body = body
}

// WithID adds the id to the update maintenance window params
func (o *UpdateMaintenanceWindowParams) WithID(id strfmt.UUID) *UpdateMaintenanceWindowParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update maintenance window params
func (o *UpdateMaintenanceWindowParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateMaintenanceWindowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
