// Code generated by go-swagger; DO NOT EDIT.

package service_request_attributes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetServiceRequestAttributeParams creates a new GetServiceRequestAttributeParams object
// with the default values initialized.
func NewGetServiceRequestAttributeParams() *GetServiceRequestAttributeParams {
	var (
		includeProcessGroupReferencesDefault = bool(false)
	)
	return &GetServiceRequestAttributeParams{
		IncludeProcessGroupReferences: &includeProcessGroupReferencesDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServiceRequestAttributeParamsWithTimeout creates a new GetServiceRequestAttributeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServiceRequestAttributeParamsWithTimeout(timeout time.Duration) *GetServiceRequestAttributeParams {
	var (
		includeProcessGroupReferencesDefault = bool(false)
	)
	return &GetServiceRequestAttributeParams{
		IncludeProcessGroupReferences: &includeProcessGroupReferencesDefault,

		timeout: timeout,
	}
}

// NewGetServiceRequestAttributeParamsWithContext creates a new GetServiceRequestAttributeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServiceRequestAttributeParamsWithContext(ctx context.Context) *GetServiceRequestAttributeParams {
	var (
		includeProcessGroupReferencesDefault = bool(false)
	)
	return &GetServiceRequestAttributeParams{
		IncludeProcessGroupReferences: &includeProcessGroupReferencesDefault,

		Context: ctx,
	}
}

// NewGetServiceRequestAttributeParamsWithHTTPClient creates a new GetServiceRequestAttributeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetServiceRequestAttributeParamsWithHTTPClient(client *http.Client) *GetServiceRequestAttributeParams {
	var (
		includeProcessGroupReferencesDefault = bool(false)
	)
	return &GetServiceRequestAttributeParams{
		IncludeProcessGroupReferences: &includeProcessGroupReferencesDefault,
		HTTPClient:                    client,
	}
}

/*GetServiceRequestAttributeParams contains all the parameters to send to the API endpoint
for the get service request attribute operation typically these are written to a http.Request
*/
type GetServiceRequestAttributeParams struct {

	/*ID
	  The ID of the required request attribute.

	*/
	ID strfmt.UUID
	/*IncludeProcessGroupReferences
	 Flag to include process group references to the response.

	Process Group group references aren't compatible across environments.

	*/
	IncludeProcessGroupReferences *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get service request attribute params
func (o *GetServiceRequestAttributeParams) WithTimeout(timeout time.Duration) *GetServiceRequestAttributeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get service request attribute params
func (o *GetServiceRequestAttributeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get service request attribute params
func (o *GetServiceRequestAttributeParams) WithContext(ctx context.Context) *GetServiceRequestAttributeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get service request attribute params
func (o *GetServiceRequestAttributeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get service request attribute params
func (o *GetServiceRequestAttributeParams) WithHTTPClient(client *http.Client) *GetServiceRequestAttributeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get service request attribute params
func (o *GetServiceRequestAttributeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get service request attribute params
func (o *GetServiceRequestAttributeParams) WithID(id strfmt.UUID) *GetServiceRequestAttributeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get service request attribute params
func (o *GetServiceRequestAttributeParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WithIncludeProcessGroupReferences adds the includeProcessGroupReferences to the get service request attribute params
func (o *GetServiceRequestAttributeParams) WithIncludeProcessGroupReferences(includeProcessGroupReferences *bool) *GetServiceRequestAttributeParams {
	o.SetIncludeProcessGroupReferences(includeProcessGroupReferences)
	return o
}

// SetIncludeProcessGroupReferences adds the includeProcessGroupReferences to the get service request attribute params
func (o *GetServiceRequestAttributeParams) SetIncludeProcessGroupReferences(includeProcessGroupReferences *bool) {
	o.IncludeProcessGroupReferences = includeProcessGroupReferences
}

// WriteToRequest writes these params to a swagger request
func (o *GetServiceRequestAttributeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if o.IncludeProcessGroupReferences != nil {

		// query param includeProcessGroupReferences
		var qrIncludeProcessGroupReferences bool
		if o.IncludeProcessGroupReferences != nil {
			qrIncludeProcessGroupReferences = *o.IncludeProcessGroupReferences
		}
		qIncludeProcessGroupReferences := swag.FormatBool(qrIncludeProcessGroupReferences)
		if qIncludeProcessGroupReferences != "" {
			if err := r.SetQueryParam("includeProcessGroupReferences", qIncludeProcessGroupReferences); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
