// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetActiveGatePluginsParams creates a new GetActiveGatePluginsParams object
// with the default values initialized.
func NewGetActiveGatePluginsParams() *GetActiveGatePluginsParams {

	return &GetActiveGatePluginsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetActiveGatePluginsParamsWithTimeout creates a new GetActiveGatePluginsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetActiveGatePluginsParamsWithTimeout(timeout time.Duration) *GetActiveGatePluginsParams {

	return &GetActiveGatePluginsParams{

		timeout: timeout,
	}
}

// NewGetActiveGatePluginsParamsWithContext creates a new GetActiveGatePluginsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetActiveGatePluginsParamsWithContext(ctx context.Context) *GetActiveGatePluginsParams {

	return &GetActiveGatePluginsParams{

		Context: ctx,
	}
}

// NewGetActiveGatePluginsParamsWithHTTPClient creates a new GetActiveGatePluginsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetActiveGatePluginsParamsWithHTTPClient(client *http.Client) *GetActiveGatePluginsParams {

	return &GetActiveGatePluginsParams{
		HTTPClient: client,
	}
}

/*GetActiveGatePluginsParams contains all the parameters to send to the API endpoint
for the get active gate plugins operation typically these are written to a http.Request
*/
type GetActiveGatePluginsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get active gate plugins params
func (o *GetActiveGatePluginsParams) WithTimeout(timeout time.Duration) *GetActiveGatePluginsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get active gate plugins params
func (o *GetActiveGatePluginsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get active gate plugins params
func (o *GetActiveGatePluginsParams) WithContext(ctx context.Context) *GetActiveGatePluginsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get active gate plugins params
func (o *GetActiveGatePluginsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get active gate plugins params
func (o *GetActiveGatePluginsParams) WithHTTPClient(client *http.Client) *GetActiveGatePluginsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get active gate plugins params
func (o *GetActiveGatePluginsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetActiveGatePluginsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
