// Code generated by go-swagger; DO NOT EDIT.

package anomaly_detection_services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// NewUpdateAnomalyDetectionServicesParams creates a new UpdateAnomalyDetectionServicesParams object
// with the default values initialized.
func NewUpdateAnomalyDetectionServicesParams() *UpdateAnomalyDetectionServicesParams {
	var ()
	return &UpdateAnomalyDetectionServicesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAnomalyDetectionServicesParamsWithTimeout creates a new UpdateAnomalyDetectionServicesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateAnomalyDetectionServicesParamsWithTimeout(timeout time.Duration) *UpdateAnomalyDetectionServicesParams {
	var ()
	return &UpdateAnomalyDetectionServicesParams{

		timeout: timeout,
	}
}

// NewUpdateAnomalyDetectionServicesParamsWithContext creates a new UpdateAnomalyDetectionServicesParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateAnomalyDetectionServicesParamsWithContext(ctx context.Context) *UpdateAnomalyDetectionServicesParams {
	var ()
	return &UpdateAnomalyDetectionServicesParams{

		Context: ctx,
	}
}

// NewUpdateAnomalyDetectionServicesParamsWithHTTPClient creates a new UpdateAnomalyDetectionServicesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateAnomalyDetectionServicesParamsWithHTTPClient(client *http.Client) *UpdateAnomalyDetectionServicesParams {
	var ()
	return &UpdateAnomalyDetectionServicesParams{
		HTTPClient: client,
	}
}

/*UpdateAnomalyDetectionServicesParams contains all the parameters to send to the API endpoint
for the update anomaly detection services operation typically these are written to a http.Request
*/
type UpdateAnomalyDetectionServicesParams struct {

	/*Body
	  The JSON body of the request. Contains parameters of the service anomaly detection configuration.

	*/
	Body *dynatrace.ServiceAnomalyDetectionConfig

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update anomaly detection services params
func (o *UpdateAnomalyDetectionServicesParams) WithTimeout(timeout time.Duration) *UpdateAnomalyDetectionServicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update anomaly detection services params
func (o *UpdateAnomalyDetectionServicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update anomaly detection services params
func (o *UpdateAnomalyDetectionServicesParams) WithContext(ctx context.Context) *UpdateAnomalyDetectionServicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update anomaly detection services params
func (o *UpdateAnomalyDetectionServicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update anomaly detection services params
func (o *UpdateAnomalyDetectionServicesParams) WithHTTPClient(client *http.Client) *UpdateAnomalyDetectionServicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update anomaly detection services params
func (o *UpdateAnomalyDetectionServicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update anomaly detection services params
func (o *UpdateAnomalyDetectionServicesParams) WithBody(body *dynatrace.ServiceAnomalyDetectionConfig) *UpdateAnomalyDetectionServicesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update anomaly detection services params
func (o *UpdateAnomalyDetectionServicesParams) SetBody(body *dynatrace.ServiceAnomalyDetectionConfig) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAnomalyDetectionServicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
