// Code generated by go-swagger; DO NOT EDIT.

package application_detection_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteApplicationDetectionRuleReader is a Reader for the DeleteApplicationDetectionRule structure.
type DeleteApplicationDetectionRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteApplicationDetectionRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteApplicationDetectionRuleNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteApplicationDetectionRuleNoContent creates a DeleteApplicationDetectionRuleNoContent with default headers values
func NewDeleteApplicationDetectionRuleNoContent() *DeleteApplicationDetectionRuleNoContent {
	return &DeleteApplicationDetectionRuleNoContent{}
}

/*DeleteApplicationDetectionRuleNoContent handles this case with default header values.

Deleted. Response doesn't have a body.
*/
type DeleteApplicationDetectionRuleNoContent struct {
}

func (o *DeleteApplicationDetectionRuleNoContent) Error() string {
	return fmt.Sprintf("[DELETE /applicationDetectionRules/{id}][%d] deleteApplicationDetectionRuleNoContent ", 204)
}

func (o *DeleteApplicationDetectionRuleNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
