// Code generated by go-swagger; DO NOT EDIT.

package application_detection_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// ValidateCreateApplicationDetectionRuleReader is a Reader for the ValidateCreateApplicationDetectionRule structure.
type ValidateCreateApplicationDetectionRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateCreateApplicationDetectionRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewValidateCreateApplicationDetectionRuleNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewValidateCreateApplicationDetectionRuleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewValidateCreateApplicationDetectionRuleNoContent creates a ValidateCreateApplicationDetectionRuleNoContent with default headers values
func NewValidateCreateApplicationDetectionRuleNoContent() *ValidateCreateApplicationDetectionRuleNoContent {
	return &ValidateCreateApplicationDetectionRuleNoContent{}
}

/*ValidateCreateApplicationDetectionRuleNoContent handles this case with default header values.

Validated. The submitted configuration is valid. Response doesn't have a body.
*/
type ValidateCreateApplicationDetectionRuleNoContent struct {
}

func (o *ValidateCreateApplicationDetectionRuleNoContent) Error() string {
	return fmt.Sprintf("[POST /applicationDetectionRules/validator][%d] validateCreateApplicationDetectionRuleNoContent ", 204)
}

func (o *ValidateCreateApplicationDetectionRuleNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateCreateApplicationDetectionRuleBadRequest creates a ValidateCreateApplicationDetectionRuleBadRequest with default headers values
func NewValidateCreateApplicationDetectionRuleBadRequest() *ValidateCreateApplicationDetectionRuleBadRequest {
	return &ValidateCreateApplicationDetectionRuleBadRequest{}
}

/*ValidateCreateApplicationDetectionRuleBadRequest handles this case with default header values.

Failed. The input is invalid.
*/
type ValidateCreateApplicationDetectionRuleBadRequest struct {
	Payload *dynatrace.ErrorEnvelope
}

func (o *ValidateCreateApplicationDetectionRuleBadRequest) Error() string {
	return fmt.Sprintf("[POST /applicationDetectionRules/validator][%d] validateCreateApplicationDetectionRuleBadRequest  %+v", 400, o.Payload)
}

func (o *ValidateCreateApplicationDetectionRuleBadRequest) GetPayload() *dynatrace.ErrorEnvelope {
	return o.Payload
}

func (o *ValidateCreateApplicationDetectionRuleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dynatrace.ErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
