// Code generated by go-swagger; DO NOT EDIT.

package automatically_applied_tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// ValidateCreateAutoTagReader is a Reader for the ValidateCreateAutoTag structure.
type ValidateCreateAutoTagReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateCreateAutoTagReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewValidateCreateAutoTagNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewValidateCreateAutoTagBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewValidateCreateAutoTagNoContent creates a ValidateCreateAutoTagNoContent with default headers values
func NewValidateCreateAutoTagNoContent() *ValidateCreateAutoTagNoContent {
	return &ValidateCreateAutoTagNoContent{}
}

/*ValidateCreateAutoTagNoContent handles this case with default header values.

Validated. The submitted configuration is valid. Response doesn't have a body.
*/
type ValidateCreateAutoTagNoContent struct {
}

func (o *ValidateCreateAutoTagNoContent) Error() string {
	return fmt.Sprintf("[POST /autoTags/validator][%d] validateCreateAutoTagNoContent ", 204)
}

func (o *ValidateCreateAutoTagNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateCreateAutoTagBadRequest creates a ValidateCreateAutoTagBadRequest with default headers values
func NewValidateCreateAutoTagBadRequest() *ValidateCreateAutoTagBadRequest {
	return &ValidateCreateAutoTagBadRequest{}
}

/*ValidateCreateAutoTagBadRequest handles this case with default header values.

Failed. The input is invalid.
*/
type ValidateCreateAutoTagBadRequest struct {
	Payload *dynatrace.ErrorEnvelope
}

func (o *ValidateCreateAutoTagBadRequest) Error() string {
	return fmt.Sprintf("[POST /autoTags/validator][%d] validateCreateAutoTagBadRequest  %+v", 400, o.Payload)
}

func (o *ValidateCreateAutoTagBadRequest) GetPayload() *dynatrace.ErrorEnvelope {
	return o.Payload
}

func (o *ValidateCreateAutoTagBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dynatrace.ErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
