// Code generated by go-swagger; DO NOT EDIT.

package anomaly_detection_disk_events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// NewValidateUpdateAnomalyDetectionDiskEventParams creates a new ValidateUpdateAnomalyDetectionDiskEventParams object
// with the default values initialized.
func NewValidateUpdateAnomalyDetectionDiskEventParams() *ValidateUpdateAnomalyDetectionDiskEventParams {
	var ()
	return &ValidateUpdateAnomalyDetectionDiskEventParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewValidateUpdateAnomalyDetectionDiskEventParamsWithTimeout creates a new ValidateUpdateAnomalyDetectionDiskEventParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewValidateUpdateAnomalyDetectionDiskEventParamsWithTimeout(timeout time.Duration) *ValidateUpdateAnomalyDetectionDiskEventParams {
	var ()
	return &ValidateUpdateAnomalyDetectionDiskEventParams{

		timeout: timeout,
	}
}

// NewValidateUpdateAnomalyDetectionDiskEventParamsWithContext creates a new ValidateUpdateAnomalyDetectionDiskEventParams object
// with the default values initialized, and the ability to set a context for a request
func NewValidateUpdateAnomalyDetectionDiskEventParamsWithContext(ctx context.Context) *ValidateUpdateAnomalyDetectionDiskEventParams {
	var ()
	return &ValidateUpdateAnomalyDetectionDiskEventParams{

		Context: ctx,
	}
}

// NewValidateUpdateAnomalyDetectionDiskEventParamsWithHTTPClient creates a new ValidateUpdateAnomalyDetectionDiskEventParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewValidateUpdateAnomalyDetectionDiskEventParamsWithHTTPClient(client *http.Client) *ValidateUpdateAnomalyDetectionDiskEventParams {
	var ()
	return &ValidateUpdateAnomalyDetectionDiskEventParams{
		HTTPClient: client,
	}
}

/*ValidateUpdateAnomalyDetectionDiskEventParams contains all the parameters to send to the API endpoint
for the validate update anomaly detection disk event operation typically these are written to a http.Request
*/
type ValidateUpdateAnomalyDetectionDiskEventParams struct {

	/*Body
	  JSON body of the request. Contains the disk event rule to be validated.

	*/
	Body *dynatrace.DiskEventAnomalyDetectionConfig
	/*ID
	  The ID of the disk event rule to be validated.

	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the validate update anomaly detection disk event params
func (o *ValidateUpdateAnomalyDetectionDiskEventParams) WithTimeout(timeout time.Duration) *ValidateUpdateAnomalyDetectionDiskEventParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate update anomaly detection disk event params
func (o *ValidateUpdateAnomalyDetectionDiskEventParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate update anomaly detection disk event params
func (o *ValidateUpdateAnomalyDetectionDiskEventParams) WithContext(ctx context.Context) *ValidateUpdateAnomalyDetectionDiskEventParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate update anomaly detection disk event params
func (o *ValidateUpdateAnomalyDetectionDiskEventParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate update anomaly detection disk event params
func (o *ValidateUpdateAnomalyDetectionDiskEventParams) WithHTTPClient(client *http.Client) *ValidateUpdateAnomalyDetectionDiskEventParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate update anomaly detection disk event params
func (o *ValidateUpdateAnomalyDetectionDiskEventParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the validate update anomaly detection disk event params
func (o *ValidateUpdateAnomalyDetectionDiskEventParams) WithBody(body *dynatrace.DiskEventAnomalyDetectionConfig) *ValidateUpdateAnomalyDetectionDiskEventParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the validate update anomaly detection disk event params
func (o *ValidateUpdateAnomalyDetectionDiskEventParams) SetBody(body *dynatrace.DiskEventAnomalyDetectionConfig) {
	o.Body = body
}

// WithID adds the id to the validate update anomaly detection disk event params
func (o *ValidateUpdateAnomalyDetectionDiskEventParams) WithID(id strfmt.UUID) *ValidateUpdateAnomalyDetectionDiskEventParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the validate update anomaly detection disk event params
func (o *ValidateUpdateAnomalyDetectionDiskEventParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateUpdateAnomalyDetectionDiskEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
