// Code generated by go-swagger; DO NOT EDIT.

package web_application_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetApplicationsWebDataPrivacyParams creates a new GetApplicationsWebDataPrivacyParams object
// with the default values initialized.
func NewGetApplicationsWebDataPrivacyParams() *GetApplicationsWebDataPrivacyParams {
	var ()
	return &GetApplicationsWebDataPrivacyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetApplicationsWebDataPrivacyParamsWithTimeout creates a new GetApplicationsWebDataPrivacyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetApplicationsWebDataPrivacyParamsWithTimeout(timeout time.Duration) *GetApplicationsWebDataPrivacyParams {
	var ()
	return &GetApplicationsWebDataPrivacyParams{

		timeout: timeout,
	}
}

// NewGetApplicationsWebDataPrivacyParamsWithContext creates a new GetApplicationsWebDataPrivacyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetApplicationsWebDataPrivacyParamsWithContext(ctx context.Context) *GetApplicationsWebDataPrivacyParams {
	var ()
	return &GetApplicationsWebDataPrivacyParams{

		Context: ctx,
	}
}

// NewGetApplicationsWebDataPrivacyParamsWithHTTPClient creates a new GetApplicationsWebDataPrivacyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetApplicationsWebDataPrivacyParamsWithHTTPClient(client *http.Client) *GetApplicationsWebDataPrivacyParams {
	var ()
	return &GetApplicationsWebDataPrivacyParams{
		HTTPClient: client,
	}
}

/*GetApplicationsWebDataPrivacyParams contains all the parameters to send to the API endpoint
for the get applications web data privacy operation typically these are written to a http.Request
*/
type GetApplicationsWebDataPrivacyParams struct {

	/*ID
	  The ID of the web application where you want to check data privacy settings.

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get applications web data privacy params
func (o *GetApplicationsWebDataPrivacyParams) WithTimeout(timeout time.Duration) *GetApplicationsWebDataPrivacyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get applications web data privacy params
func (o *GetApplicationsWebDataPrivacyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get applications web data privacy params
func (o *GetApplicationsWebDataPrivacyParams) WithContext(ctx context.Context) *GetApplicationsWebDataPrivacyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get applications web data privacy params
func (o *GetApplicationsWebDataPrivacyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get applications web data privacy params
func (o *GetApplicationsWebDataPrivacyParams) WithHTTPClient(client *http.Client) *GetApplicationsWebDataPrivacyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get applications web data privacy params
func (o *GetApplicationsWebDataPrivacyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get applications web data privacy params
func (o *GetApplicationsWebDataPrivacyParams) WithID(id string) *GetApplicationsWebDataPrivacyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get applications web data privacy params
func (o *GetApplicationsWebDataPrivacyParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetApplicationsWebDataPrivacyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
