// Code generated by go-swagger; DO NOT EDIT.

package web_application_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetApplicationsWebDataPrivacyListParams creates a new GetApplicationsWebDataPrivacyListParams object
// with the default values initialized.
func NewGetApplicationsWebDataPrivacyListParams() *GetApplicationsWebDataPrivacyListParams {

	return &GetApplicationsWebDataPrivacyListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetApplicationsWebDataPrivacyListParamsWithTimeout creates a new GetApplicationsWebDataPrivacyListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetApplicationsWebDataPrivacyListParamsWithTimeout(timeout time.Duration) *GetApplicationsWebDataPrivacyListParams {

	return &GetApplicationsWebDataPrivacyListParams{

		timeout: timeout,
	}
}

// NewGetApplicationsWebDataPrivacyListParamsWithContext creates a new GetApplicationsWebDataPrivacyListParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetApplicationsWebDataPrivacyListParamsWithContext(ctx context.Context) *GetApplicationsWebDataPrivacyListParams {

	return &GetApplicationsWebDataPrivacyListParams{

		Context: ctx,
	}
}

// NewGetApplicationsWebDataPrivacyListParamsWithHTTPClient creates a new GetApplicationsWebDataPrivacyListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetApplicationsWebDataPrivacyListParamsWithHTTPClient(client *http.Client) *GetApplicationsWebDataPrivacyListParams {

	return &GetApplicationsWebDataPrivacyListParams{
		HTTPClient: client,
	}
}

/*GetApplicationsWebDataPrivacyListParams contains all the parameters to send to the API endpoint
for the get applications web data privacy list operation typically these are written to a http.Request
*/
type GetApplicationsWebDataPrivacyListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get applications web data privacy list params
func (o *GetApplicationsWebDataPrivacyListParams) WithTimeout(timeout time.Duration) *GetApplicationsWebDataPrivacyListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get applications web data privacy list params
func (o *GetApplicationsWebDataPrivacyListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get applications web data privacy list params
func (o *GetApplicationsWebDataPrivacyListParams) WithContext(ctx context.Context) *GetApplicationsWebDataPrivacyListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get applications web data privacy list params
func (o *GetApplicationsWebDataPrivacyListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get applications web data privacy list params
func (o *GetApplicationsWebDataPrivacyListParams) WithHTTPClient(client *http.Client) *GetApplicationsWebDataPrivacyListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get applications web data privacy list params
func (o *GetApplicationsWebDataPrivacyListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetApplicationsWebDataPrivacyListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
