// Code generated by go-swagger; DO NOT EDIT.

package web_application_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetApplicationsWebsParams creates a new GetApplicationsWebsParams object
// with the default values initialized.
func NewGetApplicationsWebsParams() *GetApplicationsWebsParams {

	return &GetApplicationsWebsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetApplicationsWebsParamsWithTimeout creates a new GetApplicationsWebsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetApplicationsWebsParamsWithTimeout(timeout time.Duration) *GetApplicationsWebsParams {

	return &GetApplicationsWebsParams{

		timeout: timeout,
	}
}

// NewGetApplicationsWebsParamsWithContext creates a new GetApplicationsWebsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetApplicationsWebsParamsWithContext(ctx context.Context) *GetApplicationsWebsParams {

	return &GetApplicationsWebsParams{

		Context: ctx,
	}
}

// NewGetApplicationsWebsParamsWithHTTPClient creates a new GetApplicationsWebsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetApplicationsWebsParamsWithHTTPClient(client *http.Client) *GetApplicationsWebsParams {

	return &GetApplicationsWebsParams{
		HTTPClient: client,
	}
}

/*GetApplicationsWebsParams contains all the parameters to send to the API endpoint
for the get applications webs operation typically these are written to a http.Request
*/
type GetApplicationsWebsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get applications webs params
func (o *GetApplicationsWebsParams) WithTimeout(timeout time.Duration) *GetApplicationsWebsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get applications webs params
func (o *GetApplicationsWebsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get applications webs params
func (o *GetApplicationsWebsParams) WithContext(ctx context.Context) *GetApplicationsWebsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get applications webs params
func (o *GetApplicationsWebsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get applications webs params
func (o *GetApplicationsWebsParams) WithHTTPClient(client *http.Client) *GetApplicationsWebsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get applications webs params
func (o *GetApplicationsWebsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetApplicationsWebsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
