// Code generated by go-swagger; DO NOT EDIT.

package management_zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetManagementZonesParams creates a new GetManagementZonesParams object
// with the default values initialized.
func NewGetManagementZonesParams() *GetManagementZonesParams {

	return &GetManagementZonesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetManagementZonesParamsWithTimeout creates a new GetManagementZonesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetManagementZonesParamsWithTimeout(timeout time.Duration) *GetManagementZonesParams {

	return &GetManagementZonesParams{

		timeout: timeout,
	}
}

// NewGetManagementZonesParamsWithContext creates a new GetManagementZonesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetManagementZonesParamsWithContext(ctx context.Context) *GetManagementZonesParams {

	return &GetManagementZonesParams{

		Context: ctx,
	}
}

// NewGetManagementZonesParamsWithHTTPClient creates a new GetManagementZonesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetManagementZonesParamsWithHTTPClient(client *http.Client) *GetManagementZonesParams {

	return &GetManagementZonesParams{
		HTTPClient: client,
	}
}

/*GetManagementZonesParams contains all the parameters to send to the API endpoint
for the get management zones operation typically these are written to a http.Request
*/
type GetManagementZonesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get management zones params
func (o *GetManagementZonesParams) WithTimeout(timeout time.Duration) *GetManagementZonesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get management zones params
func (o *GetManagementZonesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get management zones params
func (o *GetManagementZonesParams) WithContext(ctx context.Context) *GetManagementZonesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get management zones params
func (o *GetManagementZonesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get management zones params
func (o *GetManagementZonesParams) WithHTTPClient(client *http.Client) *GetManagementZonesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get management zones params
func (o *GetManagementZonesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetManagementZonesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
