// Code generated by go-swagger; DO NOT EDIT.

package management_zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// GetManagementZonesReader is a Reader for the GetManagementZones structure.
type GetManagementZonesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetManagementZonesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetManagementZonesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetManagementZonesOK creates a GetManagementZonesOK with default headers values
func NewGetManagementZonesOK() *GetManagementZonesOK {
	return &GetManagementZonesOK{}
}

/*GetManagementZonesOK handles this case with default header values.

successful operation
*/
type GetManagementZonesOK struct {
	Payload *dynatrace.StubList
}

func (o *GetManagementZonesOK) Error() string {
	return fmt.Sprintf("[GET /managementZones][%d] getManagementZonesOK  %+v", 200, o.Payload)
}

func (o *GetManagementZonesOK) GetPayload() *dynatrace.StubList {
	return o.Payload
}

func (o *GetManagementZonesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dynatrace.StubList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
