// Code generated by go-swagger; DO NOT EDIT.

package log_monitoring_metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// GetCalculatedMetricsLogsReader is a Reader for the GetCalculatedMetricsLogs structure.
type GetCalculatedMetricsLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCalculatedMetricsLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCalculatedMetricsLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCalculatedMetricsLogsOK creates a GetCalculatedMetricsLogsOK with default headers values
func NewGetCalculatedMetricsLogsOK() *GetCalculatedMetricsLogsOK {
	return &GetCalculatedMetricsLogsOK{}
}

/*GetCalculatedMetricsLogsOK handles this case with default header values.

successful operation
*/
type GetCalculatedMetricsLogsOK struct {
	Payload *dynatrace.StubList
}

func (o *GetCalculatedMetricsLogsOK) Error() string {
	return fmt.Sprintf("[GET /calculatedMetrics/log][%d] getCalculatedMetricsLogsOK  %+v", 200, o.Payload)
}

func (o *GetCalculatedMetricsLogsOK) GetPayload() *dynatrace.StubList {
	return o.Payload
}

func (o *GetCalculatedMetricsLogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dynatrace.StubList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
