// Code generated by go-swagger; DO NOT EDIT.

package service_i_b_m_m_q_tracing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteServiceMqtTracingQueueManagerParams creates a new DeleteServiceMqtTracingQueueManagerParams object
// with the default values initialized.
func NewDeleteServiceMqtTracingQueueManagerParams() *DeleteServiceMqtTracingQueueManagerParams {
	var ()
	return &DeleteServiceMqtTracingQueueManagerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteServiceMqtTracingQueueManagerParamsWithTimeout creates a new DeleteServiceMqtTracingQueueManagerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteServiceMqtTracingQueueManagerParamsWithTimeout(timeout time.Duration) *DeleteServiceMqtTracingQueueManagerParams {
	var ()
	return &DeleteServiceMqtTracingQueueManagerParams{

		timeout: timeout,
	}
}

// NewDeleteServiceMqtTracingQueueManagerParamsWithContext creates a new DeleteServiceMqtTracingQueueManagerParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteServiceMqtTracingQueueManagerParamsWithContext(ctx context.Context) *DeleteServiceMqtTracingQueueManagerParams {
	var ()
	return &DeleteServiceMqtTracingQueueManagerParams{

		Context: ctx,
	}
}

// NewDeleteServiceMqtTracingQueueManagerParamsWithHTTPClient creates a new DeleteServiceMqtTracingQueueManagerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteServiceMqtTracingQueueManagerParamsWithHTTPClient(client *http.Client) *DeleteServiceMqtTracingQueueManagerParams {
	var ()
	return &DeleteServiceMqtTracingQueueManagerParams{
		HTTPClient: client,
	}
}

/*DeleteServiceMqtTracingQueueManagerParams contains all the parameters to send to the API endpoint
for the delete service mqt tracing queue manager operation typically these are written to a http.Request
*/
type DeleteServiceMqtTracingQueueManagerParams struct {

	/*Name
	  The name of the queue manager to be deleted.

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete service mqt tracing queue manager params
func (o *DeleteServiceMqtTracingQueueManagerParams) WithTimeout(timeout time.Duration) *DeleteServiceMqtTracingQueueManagerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete service mqt tracing queue manager params
func (o *DeleteServiceMqtTracingQueueManagerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete service mqt tracing queue manager params
func (o *DeleteServiceMqtTracingQueueManagerParams) WithContext(ctx context.Context) *DeleteServiceMqtTracingQueueManagerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete service mqt tracing queue manager params
func (o *DeleteServiceMqtTracingQueueManagerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete service mqt tracing queue manager params
func (o *DeleteServiceMqtTracingQueueManagerParams) WithHTTPClient(client *http.Client) *DeleteServiceMqtTracingQueueManagerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete service mqt tracing queue manager params
func (o *DeleteServiceMqtTracingQueueManagerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete service mqt tracing queue manager params
func (o *DeleteServiceMqtTracingQueueManagerParams) WithName(name string) *DeleteServiceMqtTracingQueueManagerParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete service mqt tracing queue manager params
func (o *DeleteServiceMqtTracingQueueManagerParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteServiceMqtTracingQueueManagerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
