// Code generated by go-swagger; DO NOT EDIT.

package service_i_b_m_m_q_tracing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// NewUpdateServiceMqtTracingImsEntryQueueParams creates a new UpdateServiceMqtTracingImsEntryQueueParams object
// with the default values initialized.
func NewUpdateServiceMqtTracingImsEntryQueueParams() *UpdateServiceMqtTracingImsEntryQueueParams {
	var ()
	return &UpdateServiceMqtTracingImsEntryQueueParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateServiceMqtTracingImsEntryQueueParamsWithTimeout creates a new UpdateServiceMqtTracingImsEntryQueueParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateServiceMqtTracingImsEntryQueueParamsWithTimeout(timeout time.Duration) *UpdateServiceMqtTracingImsEntryQueueParams {
	var ()
	return &UpdateServiceMqtTracingImsEntryQueueParams{

		timeout: timeout,
	}
}

// NewUpdateServiceMqtTracingImsEntryQueueParamsWithContext creates a new UpdateServiceMqtTracingImsEntryQueueParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateServiceMqtTracingImsEntryQueueParamsWithContext(ctx context.Context) *UpdateServiceMqtTracingImsEntryQueueParams {
	var ()
	return &UpdateServiceMqtTracingImsEntryQueueParams{

		Context: ctx,
	}
}

// NewUpdateServiceMqtTracingImsEntryQueueParamsWithHTTPClient creates a new UpdateServiceMqtTracingImsEntryQueueParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateServiceMqtTracingImsEntryQueueParamsWithHTTPClient(client *http.Client) *UpdateServiceMqtTracingImsEntryQueueParams {
	var ()
	return &UpdateServiceMqtTracingImsEntryQueueParams{
		HTTPClient: client,
	}
}

/*UpdateServiceMqtTracingImsEntryQueueParams contains all the parameters to send to the API endpoint
for the update service mqt tracing ims entry queue operation typically these are written to a http.Request
*/
type UpdateServiceMqtTracingImsEntryQueueParams struct {

	/*Body
	  JSON body of the request, containing updated parameters of the IBM IMS entry queue.

	*/
	Body *dynatrace.IbmMQImsEntryQueue
	/*ID
	 The ID of the IBM IMS entry queue to update.

	If you set the ID in the body as well, it must match this ID.

	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update service mqt tracing ims entry queue params
func (o *UpdateServiceMqtTracingImsEntryQueueParams) WithTimeout(timeout time.Duration) *UpdateServiceMqtTracingImsEntryQueueParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update service mqt tracing ims entry queue params
func (o *UpdateServiceMqtTracingImsEntryQueueParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update service mqt tracing ims entry queue params
func (o *UpdateServiceMqtTracingImsEntryQueueParams) WithContext(ctx context.Context) *UpdateServiceMqtTracingImsEntryQueueParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update service mqt tracing ims entry queue params
func (o *UpdateServiceMqtTracingImsEntryQueueParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update service mqt tracing ims entry queue params
func (o *UpdateServiceMqtTracingImsEntryQueueParams) WithHTTPClient(client *http.Client) *UpdateServiceMqtTracingImsEntryQueueParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update service mqt tracing ims entry queue params
func (o *UpdateServiceMqtTracingImsEntryQueueParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update service mqt tracing ims entry queue params
func (o *UpdateServiceMqtTracingImsEntryQueueParams) WithBody(body *dynatrace.IbmMQImsEntryQueue) *UpdateServiceMqtTracingImsEntryQueueParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update service mqt tracing ims entry queue params
func (o *UpdateServiceMqtTracingImsEntryQueueParams) SetBody(body *dynatrace.IbmMQImsEntryQueue) {
	o.Body = body
}

// WithID adds the id to the update service mqt tracing ims entry queue params
func (o *UpdateServiceMqtTracingImsEntryQueueParams) WithID(id strfmt.UUID) *UpdateServiceMqtTracingImsEntryQueueParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update service mqt tracing ims entry queue params
func (o *UpdateServiceMqtTracingImsEntryQueueParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateServiceMqtTracingImsEntryQueueParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
