// Code generated by go-swagger; DO NOT EDIT.

package service_i_b_m_m_q_tracing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// NewUpdateServiceMqtTracingQueueManagerParams creates a new UpdateServiceMqtTracingQueueManagerParams object
// with the default values initialized.
func NewUpdateServiceMqtTracingQueueManagerParams() *UpdateServiceMqtTracingQueueManagerParams {
	var ()
	return &UpdateServiceMqtTracingQueueManagerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateServiceMqtTracingQueueManagerParamsWithTimeout creates a new UpdateServiceMqtTracingQueueManagerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateServiceMqtTracingQueueManagerParamsWithTimeout(timeout time.Duration) *UpdateServiceMqtTracingQueueManagerParams {
	var ()
	return &UpdateServiceMqtTracingQueueManagerParams{

		timeout: timeout,
	}
}

// NewUpdateServiceMqtTracingQueueManagerParamsWithContext creates a new UpdateServiceMqtTracingQueueManagerParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateServiceMqtTracingQueueManagerParamsWithContext(ctx context.Context) *UpdateServiceMqtTracingQueueManagerParams {
	var ()
	return &UpdateServiceMqtTracingQueueManagerParams{

		Context: ctx,
	}
}

// NewUpdateServiceMqtTracingQueueManagerParamsWithHTTPClient creates a new UpdateServiceMqtTracingQueueManagerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateServiceMqtTracingQueueManagerParamsWithHTTPClient(client *http.Client) *UpdateServiceMqtTracingQueueManagerParams {
	var ()
	return &UpdateServiceMqtTracingQueueManagerParams{
		HTTPClient: client,
	}
}

/*UpdateServiceMqtTracingQueueManagerParams contains all the parameters to send to the API endpoint
for the update service mqt tracing queue manager operation typically these are written to a http.Request
*/
type UpdateServiceMqtTracingQueueManagerParams struct {

	/*Body
	  The JSON body of the request containing updated parameters of the queue manager.

	*/
	Body *dynatrace.QueueManager
	/*Name
	 The name of the queue manager to be updated.

	The name of the queue manager in the body of the request must match this name.

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update service mqt tracing queue manager params
func (o *UpdateServiceMqtTracingQueueManagerParams) WithTimeout(timeout time.Duration) *UpdateServiceMqtTracingQueueManagerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update service mqt tracing queue manager params
func (o *UpdateServiceMqtTracingQueueManagerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update service mqt tracing queue manager params
func (o *UpdateServiceMqtTracingQueueManagerParams) WithContext(ctx context.Context) *UpdateServiceMqtTracingQueueManagerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update service mqt tracing queue manager params
func (o *UpdateServiceMqtTracingQueueManagerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update service mqt tracing queue manager params
func (o *UpdateServiceMqtTracingQueueManagerParams) WithHTTPClient(client *http.Client) *UpdateServiceMqtTracingQueueManagerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update service mqt tracing queue manager params
func (o *UpdateServiceMqtTracingQueueManagerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update service mqt tracing queue manager params
func (o *UpdateServiceMqtTracingQueueManagerParams) WithBody(body *dynatrace.QueueManager) *UpdateServiceMqtTracingQueueManagerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update service mqt tracing queue manager params
func (o *UpdateServiceMqtTracingQueueManagerParams) SetBody(body *dynatrace.QueueManager) {
	o.Body = body
}

// WithName adds the name to the update service mqt tracing queue manager params
func (o *UpdateServiceMqtTracingQueueManagerParams) WithName(name string) *UpdateServiceMqtTracingQueueManagerParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the update service mqt tracing queue manager params
func (o *UpdateServiceMqtTracingQueueManagerParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateServiceMqtTracingQueueManagerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
