// Code generated by go-swagger; DO NOT EDIT.

package service_custom_services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// NewValidateCreateServiceCustomServiceParams creates a new ValidateCreateServiceCustomServiceParams object
// with the default values initialized.
func NewValidateCreateServiceCustomServiceParams() *ValidateCreateServiceCustomServiceParams {
	var ()
	return &ValidateCreateServiceCustomServiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewValidateCreateServiceCustomServiceParamsWithTimeout creates a new ValidateCreateServiceCustomServiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewValidateCreateServiceCustomServiceParamsWithTimeout(timeout time.Duration) *ValidateCreateServiceCustomServiceParams {
	var ()
	return &ValidateCreateServiceCustomServiceParams{

		timeout: timeout,
	}
}

// NewValidateCreateServiceCustomServiceParamsWithContext creates a new ValidateCreateServiceCustomServiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewValidateCreateServiceCustomServiceParamsWithContext(ctx context.Context) *ValidateCreateServiceCustomServiceParams {
	var ()
	return &ValidateCreateServiceCustomServiceParams{

		Context: ctx,
	}
}

// NewValidateCreateServiceCustomServiceParamsWithHTTPClient creates a new ValidateCreateServiceCustomServiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewValidateCreateServiceCustomServiceParamsWithHTTPClient(client *http.Client) *ValidateCreateServiceCustomServiceParams {
	var ()
	return &ValidateCreateServiceCustomServiceParams{
		HTTPClient: client,
	}
}

/*ValidateCreateServiceCustomServiceParams contains all the parameters to send to the API endpoint
for the validate create service custom service operation typically these are written to a http.Request
*/
type ValidateCreateServiceCustomServiceParams struct {

	/*Body
	  JSON body of the request containing definition of the custom service to validate.

	*/
	Body *dynatrace.CustomService
	/*Technology
	  Technology of the custom service to validate.

	*/
	Technology string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the validate create service custom service params
func (o *ValidateCreateServiceCustomServiceParams) WithTimeout(timeout time.Duration) *ValidateCreateServiceCustomServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate create service custom service params
func (o *ValidateCreateServiceCustomServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate create service custom service params
func (o *ValidateCreateServiceCustomServiceParams) WithContext(ctx context.Context) *ValidateCreateServiceCustomServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate create service custom service params
func (o *ValidateCreateServiceCustomServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate create service custom service params
func (o *ValidateCreateServiceCustomServiceParams) WithHTTPClient(client *http.Client) *ValidateCreateServiceCustomServiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate create service custom service params
func (o *ValidateCreateServiceCustomServiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the validate create service custom service params
func (o *ValidateCreateServiceCustomServiceParams) WithBody(body *dynatrace.CustomService) *ValidateCreateServiceCustomServiceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the validate create service custom service params
func (o *ValidateCreateServiceCustomServiceParams) SetBody(body *dynatrace.CustomService) {
	o.Body = body
}

// WithTechnology adds the technology to the validate create service custom service params
func (o *ValidateCreateServiceCustomServiceParams) WithTechnology(technology string) *ValidateCreateServiceCustomServiceParams {
	o.SetTechnology(technology)
	return o
}

// SetTechnology adds the technology to the validate create service custom service params
func (o *ValidateCreateServiceCustomServiceParams) SetTechnology(technology string) {
	o.Technology = technology
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateCreateServiceCustomServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param technology
	if err := r.SetPathParam("technology", o.Technology); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
