// Code generated by go-swagger; DO NOT EDIT.

package service_custom_services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// ValidateUpdateServiceCustomServiceReader is a Reader for the ValidateUpdateServiceCustomService structure.
type ValidateUpdateServiceCustomServiceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateUpdateServiceCustomServiceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewValidateUpdateServiceCustomServiceNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewValidateUpdateServiceCustomServiceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewValidateUpdateServiceCustomServiceNoContent creates a ValidateUpdateServiceCustomServiceNoContent with default headers values
func NewValidateUpdateServiceCustomServiceNoContent() *ValidateUpdateServiceCustomServiceNoContent {
	return &ValidateUpdateServiceCustomServiceNoContent{}
}

/*ValidateUpdateServiceCustomServiceNoContent handles this case with default header values.

Validated. The submitted configuration is valid. Response does not have a body.
*/
type ValidateUpdateServiceCustomServiceNoContent struct {
}

func (o *ValidateUpdateServiceCustomServiceNoContent) Error() string {
	return fmt.Sprintf("[POST /service/customServices/{technology}/{id}/validator][%d] validateUpdateServiceCustomServiceNoContent ", 204)
}

func (o *ValidateUpdateServiceCustomServiceNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateUpdateServiceCustomServiceBadRequest creates a ValidateUpdateServiceCustomServiceBadRequest with default headers values
func NewValidateUpdateServiceCustomServiceBadRequest() *ValidateUpdateServiceCustomServiceBadRequest {
	return &ValidateUpdateServiceCustomServiceBadRequest{}
}

/*ValidateUpdateServiceCustomServiceBadRequest handles this case with default header values.

Failed. The input is invalid.
*/
type ValidateUpdateServiceCustomServiceBadRequest struct {
	Payload *dynatrace.ErrorEnvelope
}

func (o *ValidateUpdateServiceCustomServiceBadRequest) Error() string {
	return fmt.Sprintf("[POST /service/customServices/{technology}/{id}/validator][%d] validateUpdateServiceCustomServiceBadRequest  %+v", 400, o.Payload)
}

func (o *ValidateUpdateServiceCustomServiceBadRequest) GetPayload() *dynatrace.ErrorEnvelope {
	return o.Payload
}

func (o *ValidateUpdateServiceCustomServiceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dynatrace.ErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
