// Code generated by go-swagger; DO NOT EDIT.

package anomaly_detection_applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// UpdateAnomalyDetectionApplicationsReader is a Reader for the UpdateAnomalyDetectionApplications structure.
type UpdateAnomalyDetectionApplicationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAnomalyDetectionApplicationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateAnomalyDetectionApplicationsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateAnomalyDetectionApplicationsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateAnomalyDetectionApplicationsNoContent creates a UpdateAnomalyDetectionApplicationsNoContent with default headers values
func NewUpdateAnomalyDetectionApplicationsNoContent() *UpdateAnomalyDetectionApplicationsNoContent {
	return &UpdateAnomalyDetectionApplicationsNoContent{}
}

/*UpdateAnomalyDetectionApplicationsNoContent handles this case with default header values.

Success. Configuration has been updated. Response doesn't have a body.
*/
type UpdateAnomalyDetectionApplicationsNoContent struct {
}

func (o *UpdateAnomalyDetectionApplicationsNoContent) Error() string {
	return fmt.Sprintf("[PUT /anomalyDetection/applications][%d] updateAnomalyDetectionApplicationsNoContent ", 204)
}

func (o *UpdateAnomalyDetectionApplicationsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateAnomalyDetectionApplicationsBadRequest creates a UpdateAnomalyDetectionApplicationsBadRequest with default headers values
func NewUpdateAnomalyDetectionApplicationsBadRequest() *UpdateAnomalyDetectionApplicationsBadRequest {
	return &UpdateAnomalyDetectionApplicationsBadRequest{}
}

/*UpdateAnomalyDetectionApplicationsBadRequest handles this case with default header values.

Failed. The input is invalid
*/
type UpdateAnomalyDetectionApplicationsBadRequest struct {
	Payload *dynatrace.ErrorEnvelope
}

func (o *UpdateAnomalyDetectionApplicationsBadRequest) Error() string {
	return fmt.Sprintf("[PUT /anomalyDetection/applications][%d] updateAnomalyDetectionApplicationsBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateAnomalyDetectionApplicationsBadRequest) GetPayload() *dynatrace.ErrorEnvelope {
	return o.Payload
}

func (o *UpdateAnomalyDetectionApplicationsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dynatrace.ErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
