// Code generated by go-swagger; DO NOT EDIT.

package service_calculated_metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// NewValidateUpdateCalculatedMetricsServiceParams creates a new ValidateUpdateCalculatedMetricsServiceParams object
// with the default values initialized.
func NewValidateUpdateCalculatedMetricsServiceParams() *ValidateUpdateCalculatedMetricsServiceParams {
	var ()
	return &ValidateUpdateCalculatedMetricsServiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewValidateUpdateCalculatedMetricsServiceParamsWithTimeout creates a new ValidateUpdateCalculatedMetricsServiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewValidateUpdateCalculatedMetricsServiceParamsWithTimeout(timeout time.Duration) *ValidateUpdateCalculatedMetricsServiceParams {
	var ()
	return &ValidateUpdateCalculatedMetricsServiceParams{

		timeout: timeout,
	}
}

// NewValidateUpdateCalculatedMetricsServiceParamsWithContext creates a new ValidateUpdateCalculatedMetricsServiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewValidateUpdateCalculatedMetricsServiceParamsWithContext(ctx context.Context) *ValidateUpdateCalculatedMetricsServiceParams {
	var ()
	return &ValidateUpdateCalculatedMetricsServiceParams{

		Context: ctx,
	}
}

// NewValidateUpdateCalculatedMetricsServiceParamsWithHTTPClient creates a new ValidateUpdateCalculatedMetricsServiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewValidateUpdateCalculatedMetricsServiceParamsWithHTTPClient(client *http.Client) *ValidateUpdateCalculatedMetricsServiceParams {
	var ()
	return &ValidateUpdateCalculatedMetricsServiceParams{
		HTTPClient: client,
	}
}

/*ValidateUpdateCalculatedMetricsServiceParams contains all the parameters to send to the API endpoint
for the validate update calculated metrics service operation typically these are written to a http.Request
*/
type ValidateUpdateCalculatedMetricsServiceParams struct {

	/*Body
	  The JSON body of the request. Contains the calculated service metric to be validated.

	*/
	Body *dynatrace.CalculatedServiceMetric
	/*MetricKey
	 The key of the calculated service metric to be validated .

	The key of the metric in the body of the request must match this key.

	*/
	MetricKey string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the validate update calculated metrics service params
func (o *ValidateUpdateCalculatedMetricsServiceParams) WithTimeout(timeout time.Duration) *ValidateUpdateCalculatedMetricsServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate update calculated metrics service params
func (o *ValidateUpdateCalculatedMetricsServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate update calculated metrics service params
func (o *ValidateUpdateCalculatedMetricsServiceParams) WithContext(ctx context.Context) *ValidateUpdateCalculatedMetricsServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate update calculated metrics service params
func (o *ValidateUpdateCalculatedMetricsServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate update calculated metrics service params
func (o *ValidateUpdateCalculatedMetricsServiceParams) WithHTTPClient(client *http.Client) *ValidateUpdateCalculatedMetricsServiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate update calculated metrics service params
func (o *ValidateUpdateCalculatedMetricsServiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the validate update calculated metrics service params
func (o *ValidateUpdateCalculatedMetricsServiceParams) WithBody(body *dynatrace.CalculatedServiceMetric) *ValidateUpdateCalculatedMetricsServiceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the validate update calculated metrics service params
func (o *ValidateUpdateCalculatedMetricsServiceParams) SetBody(body *dynatrace.CalculatedServiceMetric) {
	o.Body = body
}

// WithMetricKey adds the metricKey to the validate update calculated metrics service params
func (o *ValidateUpdateCalculatedMetricsServiceParams) WithMetricKey(metricKey string) *ValidateUpdateCalculatedMetricsServiceParams {
	o.SetMetricKey(metricKey)
	return o
}

// SetMetricKey adds the metricKey to the validate update calculated metrics service params
func (o *ValidateUpdateCalculatedMetricsServiceParams) SetMetricKey(metricKey string) {
	o.MetricKey = metricKey
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateUpdateCalculatedMetricsServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param metricKey
	if err := r.SetPathParam("metricKey", o.MetricKey); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
