// Code generated by go-swagger; DO NOT EDIT.

package service_calculated_metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// NewValidateCreateCalculatedMetricsServiceParams creates a new ValidateCreateCalculatedMetricsServiceParams object
// with the default values initialized.
func NewValidateCreateCalculatedMetricsServiceParams() *ValidateCreateCalculatedMetricsServiceParams {
	var ()
	return &ValidateCreateCalculatedMetricsServiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewValidateCreateCalculatedMetricsServiceParamsWithTimeout creates a new ValidateCreateCalculatedMetricsServiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewValidateCreateCalculatedMetricsServiceParamsWithTimeout(timeout time.Duration) *ValidateCreateCalculatedMetricsServiceParams {
	var ()
	return &ValidateCreateCalculatedMetricsServiceParams{

		timeout: timeout,
	}
}

// NewValidateCreateCalculatedMetricsServiceParamsWithContext creates a new ValidateCreateCalculatedMetricsServiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewValidateCreateCalculatedMetricsServiceParamsWithContext(ctx context.Context) *ValidateCreateCalculatedMetricsServiceParams {
	var ()
	return &ValidateCreateCalculatedMetricsServiceParams{

		Context: ctx,
	}
}

// NewValidateCreateCalculatedMetricsServiceParamsWithHTTPClient creates a new ValidateCreateCalculatedMetricsServiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewValidateCreateCalculatedMetricsServiceParamsWithHTTPClient(client *http.Client) *ValidateCreateCalculatedMetricsServiceParams {
	var ()
	return &ValidateCreateCalculatedMetricsServiceParams{
		HTTPClient: client,
	}
}

/*ValidateCreateCalculatedMetricsServiceParams contains all the parameters to send to the API endpoint
for the validate create calculated metrics service operation typically these are written to a http.Request
*/
type ValidateCreateCalculatedMetricsServiceParams struct {

	/*Body
	  The JSON body of the request. Contains the calculated service metric to be validated.

	*/
	Body *dynatrace.CalculatedServiceMetric

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the validate create calculated metrics service params
func (o *ValidateCreateCalculatedMetricsServiceParams) WithTimeout(timeout time.Duration) *ValidateCreateCalculatedMetricsServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate create calculated metrics service params
func (o *ValidateCreateCalculatedMetricsServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate create calculated metrics service params
func (o *ValidateCreateCalculatedMetricsServiceParams) WithContext(ctx context.Context) *ValidateCreateCalculatedMetricsServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate create calculated metrics service params
func (o *ValidateCreateCalculatedMetricsServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate create calculated metrics service params
func (o *ValidateCreateCalculatedMetricsServiceParams) WithHTTPClient(client *http.Client) *ValidateCreateCalculatedMetricsServiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate create calculated metrics service params
func (o *ValidateCreateCalculatedMetricsServiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the validate create calculated metrics service params
func (o *ValidateCreateCalculatedMetricsServiceParams) WithBody(body *dynatrace.CalculatedServiceMetric) *ValidateCreateCalculatedMetricsServiceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the validate create calculated metrics service params
func (o *ValidateCreateCalculatedMetricsServiceParams) SetBody(body *dynatrace.CalculatedServiceMetric) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateCreateCalculatedMetricsServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
