// Code generated by go-swagger; DO NOT EDIT.

package dynatrace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OverloadedStorageThresholds Custom thresholds for overloaded storage on physical storage device. If not set then the automatic mode is used.
// swagger:model OverloadedStorageThresholds
type OverloadedStorageThresholds struct {

	// Alert if number of command aborts is higher than *X* in 3 out of 5 samples.
	// Required: true
	// Maximum: 100
	// Minimum: 0
	CommandAbortsNumber *int32 `json:"commandAbortsNumber"`
}

// Validate validates this overloaded storage thresholds
func (m *OverloadedStorageThresholds) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCommandAbortsNumber(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OverloadedStorageThresholds) validateCommandAbortsNumber(formats strfmt.Registry) error {

	if err := validate.Required("commandAbortsNumber", "body", m.CommandAbortsNumber); err != nil {
		return err
	}

	if err := validate.MinimumInt("commandAbortsNumber", "body", int64(*m.CommandAbortsNumber), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("commandAbortsNumber", "body", int64(*m.CommandAbortsNumber), 100, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OverloadedStorageThresholds) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OverloadedStorageThresholds) UnmarshalBinary(b []byte) error {
	var res OverloadedStorageThresholds
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
