// Code generated by go-swagger; DO NOT EDIT.

package dynatrace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RdsHighCPUThresholds Custom thresholds for high CPU utilization on RDS. If not set, automatic mode is used.
// swagger:model RdsHighCpuThresholds
type RdsHighCPUThresholds struct {

	// Alert if CPU usage is higher than *X*% in 3 out of 5 samples.
	// Required: true
	// Maximum: 100
	// Minimum: 1
	CPUUsagePercentage *int32 `json:"cpuUsagePercentage"`
}

// Validate validates this rds high Cpu thresholds
func (m *RdsHighCPUThresholds) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCPUUsagePercentage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RdsHighCPUThresholds) validateCPUUsagePercentage(formats strfmt.Registry) error {

	if err := validate.Required("cpuUsagePercentage", "body", m.CPUUsagePercentage); err != nil {
		return err
	}

	if err := validate.MinimumInt("cpuUsagePercentage", "body", int64(*m.CPUUsagePercentage), 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("cpuUsagePercentage", "body", int64(*m.CPUUsagePercentage), 100, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RdsHighCPUThresholds) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RdsHighCPUThresholds) UnmarshalBinary(b []byte) error {
	var res RdsHighCPUThresholds
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
