// Code generated by go-swagger; DO NOT EDIT.

package dynatrace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TokenCredentials token credentials
// swagger:model TokenCredentials
type TokenCredentials struct {
	descriptionField *string

	idField string

	nameField *string

	ownerAccessOnlyField bool

	// Token in the string format.
	// Required: true
	Token *string `json:"token"`
}

// Description gets the description of this subtype
func (m *TokenCredentials) Description() *string {
	return m.descriptionField
}

// SetDescription sets the description of this subtype
func (m *TokenCredentials) SetDescription(val *string) {
	m.descriptionField = val
}

// ID gets the id of this subtype
func (m *TokenCredentials) ID() string {
	return m.idField
}

// SetID sets the id of this subtype
func (m *TokenCredentials) SetID(val string) {
	m.idField = val
}

// Name gets the name of this subtype
func (m *TokenCredentials) Name() *string {
	return m.nameField
}

// SetName sets the name of this subtype
func (m *TokenCredentials) SetName(val *string) {
	m.nameField = val
}

// OwnerAccessOnly gets the owner access only of this subtype
func (m *TokenCredentials) OwnerAccessOnly() bool {
	return m.ownerAccessOnlyField
}

// SetOwnerAccessOnly sets the owner access only of this subtype
func (m *TokenCredentials) SetOwnerAccessOnly(val bool) {
	m.ownerAccessOnlyField = val
}

// Type gets the type of this subtype
func (m *TokenCredentials) Type() string {
	return "TokenCredentials"
}

// SetType sets the type of this subtype
func (m *TokenCredentials) SetType(val string) {

}

// Token gets the token of this subtype

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *TokenCredentials) UnmarshalJSON(raw []byte) error {
	var data struct {

		// Token in the string format.
		// Required: true
		Token *string `json:"token"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		Description *string `json:"description"`

		ID string `json:"id,omitempty"`

		Name *string `json:"name"`

		OwnerAccessOnly bool `json:"ownerAccessOnly,omitempty"`

		Type string `json:"type"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result TokenCredentials

	result.descriptionField = base.Description

	result.idField = base.ID

	result.nameField = base.Name

	result.ownerAccessOnlyField = base.OwnerAccessOnly

	if base.Type != result.Type() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid type value: %q", base.Type)
	}

	result.Token = data.Token

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m TokenCredentials) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {

		// Token in the string format.
		// Required: true
		Token *string `json:"token"`
	}{

		Token: m.Token,
	},
	)
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		Description *string `json:"description"`

		ID string `json:"id,omitempty"`

		Name *string `json:"name"`

		OwnerAccessOnly bool `json:"ownerAccessOnly,omitempty"`

		Type string `json:"type"`
	}{

		Description: m.Description(),

		ID: m.ID(),

		Name: m.Name(),

		OwnerAccessOnly: m.OwnerAccessOnly(),

		Type: m.Type(),
	},
	)
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this token credentials
func (m *TokenCredentials) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TokenCredentials) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description()); err != nil {
		return err
	}

	return nil
}

func (m *TokenCredentials) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name()); err != nil {
		return err
	}

	return nil
}

func (m *TokenCredentials) validateToken(formats strfmt.Registry) error {

	if err := validate.Required("token", "body", m.Token); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TokenCredentials) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TokenCredentials) UnmarshalBinary(b []byte) error {
	var res TokenCredentials
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
