// Code generated by go-swagger; DO NOT EDIT.

package service_detection_opaque_and_external_web_request

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Kissy/go-dynatrace/dynatrace"
)

// NewUpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams creates a new UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams object
// with the default values initialized.
func NewUpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams() *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams {
	var ()
	return &UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParamsWithTimeout creates a new UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParamsWithTimeout(timeout time.Duration) *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams {
	var ()
	return &UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams{

		timeout: timeout,
	}
}

// NewUpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParamsWithContext creates a new UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParamsWithContext(ctx context.Context) *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams {
	var ()
	return &UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams{

		Context: ctx,
	}
}

// NewUpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParamsWithHTTPClient creates a new UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParamsWithHTTPClient(client *http.Client) *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams {
	var ()
	return &UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams{
		HTTPClient: client,
	}
}

/*UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams contains all the parameters to send to the API endpoint
for the update service detection rule opaque and external requests order operation typically these are written to a http.Request
*/
type UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams struct {

	/*Body
	  The JSON body of the request containing the service detection rules in the required order.

	*/
	Body *dynatrace.StubList

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update service detection rule opaque and external requests order params
func (o *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams) WithTimeout(timeout time.Duration) *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update service detection rule opaque and external requests order params
func (o *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update service detection rule opaque and external requests order params
func (o *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams) WithContext(ctx context.Context) *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update service detection rule opaque and external requests order params
func (o *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update service detection rule opaque and external requests order params
func (o *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams) WithHTTPClient(client *http.Client) *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update service detection rule opaque and external requests order params
func (o *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update service detection rule opaque and external requests order params
func (o *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams) WithBody(body *dynatrace.StubList) *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update service detection rule opaque and external requests order params
func (o *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams) SetBody(body *dynatrace.StubList) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateServiceDetectionRuleOpaqueAndExternalRequestsOrderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
